import '@/styles/reset.css';
import '@/styles/globals.css';

import localFont from 'next/font/local';

import type { Metadata } from 'next';

import { appFrame, appShell } from '@/app/layout.css';
import { themeClass } from '@/styles/theme.css';

const pretendard = localFont({
  src: [
    { path: '../fonts/Pretendard-ExtraLight.woff', weight: '200' },
    { path: '../fonts/Pretendard-Light.woff', weight: '300' },
    { path: '../fonts/Pretendard-Regular.woff', weight: '400' },
    { path: '../fonts/Pretendard-Medium.woff', weight: '500' },
    { path: '../fonts/Pretendard-SemiBold.woff', weight: '600' },
    { path: '../fonts/Pretendard-Bold.woff', weight: '700' },
    { path: '../fonts/Pretendard-ExtraBold.woff', weight: '800' },
  ],
  display: 'swap',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.className} ${themeClass}`}>
      <body>
        <div className={appShell}>
          <div className={appFrame}>{children}</div>
        </div>
      </body>
    </html>
  );
}
