import '@/styles/reset.css';
import '@/styles/globals.css';

import localFont from 'next/font/local';
import { Toaster } from 'react-hot-toast';

import Providers from '@/app/providers';
import { KakaoMapPreload } from '@/components/kakao/KakaoMapPreload';
import { getServerQueryScope } from '@/libs/query/getServerQueryScope';

import type { Metadata } from 'next';

import { appFrame, appShell } from '@/app/layout.css';
import { themeClass } from '@/styles/theme.css';

const pretendard = localFont({
  src: [
    { path: '../fonts/Pretendard-Regular.woff2', weight: '400' },
    { path: '../fonts/Pretendard-Medium.woff2', weight: '500' },
    { path: '../fonts/Pretendard-SemiBold.woff2', weight: '600' },
    { path: '../fonts/Pretendard-Bold.woff2', weight: '700' },
  ],
  display: 'swap',
  preload: false,
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryScope = await getServerQueryScope();

  return (
    <html lang="en" className={`${pretendard.variable} ${themeClass}`}>
      <body>
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 4000,
            style: {
              background: '#363636',
              color: '#fff',
            },
          }}
        />
        <KakaoMapPreload />
        <Providers initialQueryScope={queryScope}>
          <div className={appShell}>
            <div className={appFrame}>{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
