import '@/styles/reset.css';
import localFont from 'next/font/local';

import type { Metadata } from 'next';

const pretendard = localFont({
  src: [
    { path: '../public/fonts/Pretendard-ExtraLight.woff', weight: '200' },
    { path: '../public/fonts/Pretendard-Light.woff', weight: '300' },
    { path: '../public/fonts/Pretendard-Regular.woff', weight: '400' },
    { path: '../public/fonts/Pretendard-Medium.woff', weight: '500' },
    { path: '../public/fonts/Pretendard-SemiBold.woff', weight: '600' },
    { path: '../public/fonts/Pretendard-Bold.woff', weight: '700' },
    { path: '../public/fonts/Pretendard-ExtraBold.woff', weight: '800' },
  ],
  variable: '--font-pretendard',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={pretendard.className}>
      <body>{children}</body>
    </html>
  );
}
